### ISSUE TITLE
[Feature Request] add video.start_on/video.end_on or a similar option

### ISSUE THREAD

**Issue by therealadityashankar** [mifi/editly#106]
say one wants to put a shorter video inside a longer video,
the current way to do that would be to divide the longer video into 3 clips

|clip 1| clip 2 | clip 3 |
|-------|-------- |--------|
|video 1 - start|video 1 - where you want both | video 1 -end |
|--|video 2|--|

and this is personally annoying and messy since the user will have to create 3 different clips just to put 1 clip inside another - this gets even messier if you wanna put multiple clips inside one another

but with specifying the start_on and end_on parameters you should be put all videos in one clip

**Comment by mifi** [comment]
I think you can use clips[].layers[].start and stop

**Comment by therealadityashankar** [comment]
You're right, my apologies for not reading carefully
