### ISSUE TITLE
[Bug] Can't use editly on ubuntu and in docker, gives segmentation error and undefined symbol: fribidi_get_bracket error

### ISSUE THREAD

**Issue by rm-rf-everything** [mifi/editly#109]
**Update 3**
Running the code locally in linux with node version 12.x and with ffmpeg 4.x throws segmentation fault error (both in Ubuntu 18 and 20, i checked #41 and it was mentioned that somehow the error was bypassed with older ffmpeg and ubuntu 18.x) but with older ffmpeg versions i can't use arbitrary audio as it throws option not found error, which is mentioned below. Any help here would be much appreciated.

****Error message****: 
```
Command was killed with SIGSEGV (Segmentation fault): ffmpeg -hide_banner -loglevel error -i /home/sameer/Documents/util/ffmpeg-output/eSDT1MfAZcRcvBsaj/editly-tmp-6_596utnG9aBYzDgZmmDC/clip0-audio.flac -i /home/sameer/Documents/util/ffmpeg-output/eSDT1MfAZcRcvBsaj/editly-tmp-6_596utnG9aBYzDgZmmDC/clip1-audio.flac -i /home/sameer/Documents/util/ffmpeg-output/eSDT1MfAZcRcvBsaj.../editly-tmp-6_596utnG9aBYzDgZmmDC/clip5-audio.flac -filter_complex [0:a][1:a]acrossfade=d=0.0001:c1=tri:c2=tri[concat0],[concat0][2:a]acrossfade=d=0.0001:c1=tri:c2=tri[concat1],[concat1][3:a]acrossfade=d=0.1:c1=tri:c2=tri[concat2],[concat2][4:a]acrossfade=d=0.0001:c1=tri:c2=tri[concat3],[concat3][5:a]acrossfade=d=0.1:c1=tri:c2=tri -c flac -y util/ffmpeg-output/eSDT1MfAZcRcvBsaj/editly-tmp-6_596utnG9aBYzDgZmmDC/audio-concat.flac'

```

**Update 2**
Installing ffmpeg from apt-get gave me the ffmpeg 3.2.15 version so i tried building a docker image from modifying the Dockerfile from this repo and as expected i got the newer version of ffmpeg which is 4.3.1 but i got a different error while mixing.

****Error****:
```
ffmpeg version 4.3.1

ffprobe version 4.3.1

Fontconfig error: Cannot load default config file

Extracting audio/silence from all clips

Mixing clip audio with arbitrary audio

720x1280 30fps

0% node: symbol lookup error: /app/node_modules/canvas/build/Release/libpango-1.0.so.0: undefined symbol: fribidi_get_bracket
```
****Updated Dockerfile****

```
FROM jrottenberg/ffmpeg:4.3.1-ubuntu1804

WORKDIR /app

# Ensures tzinfo doesn't ask for region info.
ENV DEBIAN_FRONTEND noninteractive

## INSTALL NODE VIA NVM

RUN apt-get update && apt-get install -y \
    dumb-init \
    xvfb

# Source: https://gist.github.com/remarkablemark/aacf14c29b3f01d6900d13137b21db3a
# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# update the repository sources list
# and install dependencies
RUN apt-get update \
    && apt-get install -y curl \
    && apt-get -y autoclean

# nvm environment variables
ENV NVM_VERSION 0.37.2
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 12.18.4

# install nvm
# https://github.com/creationix/nvm#install-script
RUN mkdir -p $NVM_DIR \
    && curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v${NVM_VERSION}/install.sh | bash

# install node and npm
RUN source ${NVM_DIR}/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

# add node and npm to path so the commands are available
ENV NODE_PATH ${NVM_DIR}/v${NODE_VERSION}/lib/node_modules
ENV PATH      ${NVM_DIR}/versions/node/v${NODE_VERSION}/bin:$PATH

# confirm installation
RUN node -v
RUN npm -v

## INSTALL EDITLY

# ## Install app dependencies
COPY package.json /app/
RUN npm install

# Add app source
COPY . /app

# Ensure `editly` binary available in container
RUN npm link

ENTRYPOINT ["/usr/bin/dumb-init", "--", "xvfb-run", "--server-args", "-screen 0 1280x1024x24 -ac"]

EXPOSE 8485

CMD [ "node", "index.js" ]
```

**Update**
Same exact code works fine in local setup (windows) but as soon as i build a docker image and try out the image i just built, it throws the below error.
Node version being used in docker image - 12.18.1
ffmpeg version - 3.2.15

**Dockerfile**
```
FROM node:12.18.1

RUN apt-get update && apt-get install -y \
    libcairo2-dev \
    libpango1.0-dev \
    libjpeg-dev \
    libgif-dev \
    librsvg2-dev \
    libxi-dev \
    libglu1-mesa-dev \
    libglew-dev \
    python2.7 \
    python-pip \
    ffmpeg \
    xvfb

ENV PORT=8485

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "/usr/src/app/"]

RUN npm install --production

ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 /usr/bin/dumb-init
RUN chmod 0777 /usr/bin/dumb-init

COPY . /usr/src/app

ENTRYPOINT ["/usr/bin/dumb-init", "--", "xvfb-run", "-s", "-ac -screen 0 1280x1024x24"]

EXPOSE 8485

CMD [ "node", "index.js" ]
```

**Versions affected:**
0.11.0
0.11.1

**Error message:**
```
Exception occured: Error: Command failed with exit code 1: ffmpeg -hide_banner -loglevel error -stream_loop 0 -i util/ffmpeg-output/eSDT1MfAZcRcvBsaj/editly-tmp-_ycLEv2mROmWeiKM-B65k/audio-concat.flac -stream_loop 0 -i ./audio.mp3 -filter_complex [0]atrim=start=0,adelay=delays=0:all=1[a0];[1]atrim=start=0,adelay=delays=0:all=1,apad[a1];[a0][a1]amix=inputs=2:duration=first:dropout_transition=0:weights=90 1,dynaudnorm=g=3:maxgain=100 -c:a flac -y util/ffmpeg-output/eSDT1MfAZcRcvBsaj/editly-tmp-_ycLEv2mROmWeiKM-B65k/audio-mixed.flac
[Parsed_adelay_1 @ 0x564554f24360] Option 'all' not found
[AVFilterGraph @ 0x564554eec780] Error initializing filter 'adelay' with args 'delays=0:all=1'
Error initializing complex filters.
Option not found
```

**EditSpec**
```
{
  "width": 720,
  "height": 1280,
  "fps": 30,
  "defaults": {
    "transition": {
      "name": "random",
      "duration": 0
    },
    "layer": {
      "fontPath": "./Poppins-Regular.ttf"
    }
  },
  "keepSourceAudio": true,
  "fast": true,
  "outPath": "./util/ffmpeg-output/eSDT1MfAZcRcvBsaj/eSDT1MfAZcRcvBsaj.mp4",
  "clips": [
    {
      "duration": 3,
      "layers": [
        {
          "type": "image",
          "path": "./confetti.jpg"
        },
        {
          "type": "title",
          "position": {
            "x": 0.5,
            "y": 0.5,
            "originX": "center",
            "originY": "center"
          },
          "text": "Blah Blah!",
          "zoomDirection": "in",
          "textColor": "#000000"
        }
      ]
    },
    {
      "transition": {
        "name": "random",
        "duration": 0.1
      },
      "layers": [
        {
          "type": "video",
          "path": "./util/downloaded-data//eSDT1MfAZcRcvBsaj/1a9062a3-0b01-3f7c-a34e-c3d15959ef1f.mp4",
          "cutFrom": 0,
          "cutTo": 9.5
        },
        {
          "type": "image-overlay",
          "path": "./overlay.svg",
          "width": 0.2,
          "position": {
            "x": 0.95,
            "y": 0.03,
            "originX": "right"
          }
        }
      ]
    },
    {
      "transition": {
        "name": "random",
        "duration": 0.1
      },
      "layers": [
        {
          "type": "video",
          "path": "./util/downloaded-data//eSDT1MfAZcRcvBsaj/7f0f5cf8-ffc5-2f42-d579-d268a61b688b.mp4",
          "cutFrom": 0,
          "cutTo": 5.5
        },
        {
          "type": "image-overlay",
          "path": "./overlay.svg",
          "width": 0.2,
          "position": {
            "x": 0.95,
            "y": 0.03,
            "originX": "right"
          }
        }
      ]
    },
    {
      "duration": 3,
      "layers": [
        {
          "type": "image",
          "path": "./confetti.svg",
          "zoomDirection": "out"
        }
      ]
    }
  ],
  "clipsAudioVolume": 90,
  "audioNorm": {
    "enable": true,
    "gaussSize": 3,
    "maxGain": 100
  },
  "audioTracks": [
    {
      "path": "./audio.mp3",
      "mixVolume": 1,
      "start": 0
    }
  ]
}
```

**Comment by rm-rf-everything** [comment]
@mifi apparently i can't use editly now with the v0.11.0 and v0.11.1 in docker even without the arbitrary audio tracks

**Comment by elkernel128** [comment]
Hi, tengo el mismo problema con la version 0.11.1 y usando el docker, pero no precisamente con el audio, tengo un solo clip con muchas capas. Para reproducir el error fui agregando capas una por una y a la 10ma capa aparecio a salir el error.

**Comment by rm-rf-everything** [comment]
Hi @elkernel128, do you get the same undefined symbol error? With the v0.11.x i can't use editly in docker for even a simple mix of two videos, it throws me the error of undefined symbol. At first i thought the usage of arbitrary audio tracks caused the error, later i commented out that code and built a fresh docker image but still no luck, same error again. So audio is not the culprit here.

**Comment by elkernel128** [comment]
yes @rm-rf-everything i got the same error that you describe above, can i run several of examples include in repo, but when do my own edition i got the error, its a shame because a docker solution its very useful for me to deployed in the cloud, when run locally in my own system works fine. i'll tried an other solution for the cloud instead. If any one has solution please share with us will be great. thanks.

**Comment by rm-rf-everything** [comment]
For all those who are still stuck, i got it working using the static ffmpeg build. [Check this for more info.](https://johnvansickle.com/ffmpeg/)

****Working Dockerfile****
```
FROM node:14.15.4-slim

WORKDIR /app

# Ensures tzinfo doesn't ask for region info.
ENV DEBIAN_FRONTEND noninteractivesdsd

RUN apt-get update && apt-get install -y wget \
    xz-utils \
    dumb-init \
    xvfb 
    
# Get ffmpeg and ffprobe with static build
RUN wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz \ 
    && tar xvf ffmpeg-release-amd64-static.tar.xz \
    && cp ffmpeg-4.3.1-amd64-static/ffmpeg /usr/local/bin/ \
    && cp ffmpeg-4.3.1-amd64-static/ffprobe /usr/local/bin/ \
    && rm -rf ffmpeg-release-amd64-static.tar.xz \
    && rm -rf ffmpeg-4.3.1-amd64-static

# Ensure ffmpeg and ffprobe are successfully copied
RUN ffmpeg -version && ffprobe -version

# ## Install app dependencies
COPY package.json /app/
RUN npm install --production

# Add app source
COPY . /app

# Ensure `editly` binary available in container
RUN npm link

ENTRYPOINT ["/usr/bin/dumb-init", "--", "xvfb-run", "--server-args", "-screen 0 1280x1024x24 -ac"]

CMD [ "node", "index.js" ]
```

**Comment by rm-rf-everything** [comment]
@elkernel128 try the above solution, might work for you :)

**Comment by elkernel128** [comment]
Great news @rm-rf-everything , i'll tried this and i'll do you known. Thanks  in advance

**Comment by Pythonista7** [comment]
> RUN wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz \

The new 

> ffmpeg-4.3.1-amd64-static/ffmpeg /usr/local/bin/

Updated , the url ` https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz ` now points to the newest ffmpeg release 4.4 , use this docker file https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz

**Comment by AmitDJagtap** [comment]
@adatta02 in your docker build ..  ffmpeg is not getting installed for some reason

on Run we get error 

`spawn ffprobe ENOENT
320x320 10fps
  0% Error: Command failed with ENOENT: ffmpeg -hide_banner -loglevel error -f rawvideo -vcodec rawvideo -pix_fmt rgba -s 320x320 -r 10 -i - -vf format=rgb24,fps=10,scale=320:320:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse -loop 0 -y ./customCanvas.gif
spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-hide_banner',
    '-loglevel',
    'error',
    '-f',
    'rawvideo',
    '-vcodec',
    'rawvideo',
    '-pix_fmt',
    'rgba',
    '-s',
    '320x320',
    '-r',
    '10',
    '-i',
    '-',
    '-vf',
    'format=rgb24,fps=10,scale=320:320:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse',
    '-loop',
    0,
    '-y',
    './customCanvas.gif'
  ],
  originalMessage: 'spawn ffmpeg ENOENT',
  shortMessage: 'Command failed with ENOENT: ffmpeg -hide_banner -loglevel error -f rawvideo -vcodec rawvideo -pix_fmt rgba -s 320x320 -r 10 -i - -vf format=rgb24,fps=10,scale=320:320:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse -loop 0 -y ./customCanvas.gif\n' +
    'spawn ffmpeg ENOENT',
  command: 'ffmpeg -hide_banner -loglevel error -f rawvideo -vcodec rawvideo -pix_fmt rgba -s 320x320 -r 10 -i - -vf format=rgb24,fps=10,scale=320:320:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse -loop 0 -y ./customCanvas.gif',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
`

**Comment by AmitDJagtap** [comment]
To make it work I used below dockerfile

`FROM ubuntu:focal-20210921

WORKDIR /app

# Ensures tzinfo doesn't ask for region info.
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y \
    dumb-init \
    xvfb \
    build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config

# Source: https://gist.github.com/remarkablemark/aacf14c29b3f01d6900d13137b21db3a
# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# update the repository sources list
# and install dependencies
RUN apt-get update \
    && apt-get install -y curl \
    && apt-get -y autoclean

RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -

RUN apt-get install -y nodejs

# confirm installation
RUN node -v
RUN npm -v

## INSTALL EDITLY

# ## Install app dependencies
COPY package.json /app/
RUN npm install

# Add app source
COPY . /app

# Ensure `editly` binary available in container
RUN npm link

RUN apt-get update && apt-get install -y wget \
    xz-utils \
    dumb-init \
    xvfb

# Get ffmpeg and ffprobe with static build
RUN wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-4.3.1-amd64-static.tar.xz \
    && tar xvf ffmpeg-4.3.1-amd64-static.tar.xz \
    && cp ffmpeg-4.3.1-amd64-static/ffmpeg /usr/local/bin/ \
    && cp ffmpeg-4.3.1-amd64-static/ffprobe /usr/local/bin/ \
    && rm -rf ffmpeg-4.3.1-amd64-static.tar.xz \
    && rm -rf ffmpeg-4.3.1-amd64-static

# Ensure ffmpeg and ffprobe are successfully copied
RUN ffmpeg -version && ffprobe -version

ENTRYPOINT ["/usr/bin/dumb-init", "--", "xvfb-run", "--server-args", "-screen 0 1280x1024x24 -ac"]

CMD [ "npm","start" ]
`

**Comment by QaisarRajput** [comment]
For all the people struggling (like i did) to install editly. I found a way using docker. Below is my environment

- WSL2
- Ubuntu 22.04
- Windows 10
- Docker Desktop

Rather than building the docker image, there is one already created on dockerhub. Follow the instructions to use.
https://hub.docker.com/r/vimagick/editly

Note: The version of different packages may not be latest. I haven't checked what's inside the image
