### ISSUE TITLE
[Feature Request] Run editly on all files in a directory?

### ISSUE THREAD

**Issue by bradr** [mifi/editly#110]
Is there any way to run editly on all files in a directory?

Something like this:
editly title:"All my videos" files/*.mp4 --out all_my_files.mp4

**Comment by thebrucecgit** [comment]
I'm not involved with this repo, but you can probably just write your own script using Node's `fs.readdir` function (probably filtering out the relevant files with [glob](https://github.com/isaacs/node-glob)), and then simply iterate editly through each file.

**Comment by mifi** [comment]
Actually what happens if you run this command? It might actually work
```
editly title:"All my videos" files/*.mp4 --out all_my_files.mp4
```

**Comment by bradr** [comment]
Caught error [Error: ENOENT: no such file or directory, stat '/files/*.mp4']

It seems stat doesn't allow wildcards. Maybe need to use glob?
https://www.npmjs.com/package/glob

**Comment by mifi** [comment]
which operating system / shell are you on?

**Comment by mifi** [comment]
I just tried the command on MacOS and here it works. So I'm guessing you are on windows which doesn't support globbing like bash does.

**Comment by bradr** [comment]
I'm running it in Windows - that makes sense! I was playing with the docker build but was having some issues, so I've been running it in powershell instead. I'll go back to my docker build, or maybe try bash through WSL. Thanks for looking into this!
