### ISSUE TITLE
Quality of image-overlay when it's visible on dark canvas

### ISSUE THREAD

**Issue by maddygoround** [mifi/editly#114]
I am trying to resize the videos to 9:16 with a logo watermarking. I notice the quality of the logo when visible on a dark background is not good. 

Also in a few of the videos, I notice there are one or two extra frames generated after the video streams end, which creates an extra frame in the video with a dark background, which again causes the same low-quality logo watermarking issue.

This is the frame being generated by fabric 
![image_27](https://user-images.githubusercontent.com/7420749/108583727-c3dd1500-7361-11eb-998f-da8ebfe3fd01.png)

And this is the final output on the video - 
<img width="458" alt="Screen Shot 2021-02-20 at 9 56 05 AM" src="https://user-images.githubusercontent.com/7420749/108583746-e4a56a80-7361-11eb-843a-a07b39145073.png">

And this is the image I am using 
![white](https://user-images.githubusercontent.com/7420749/108583800-3d750300-7362-11eb-9bcb-c2efb35babd6.png)

The above logo image is transparent, so you might able to see it at first.

**Comment by mifi** [comment]
See #84 :)
