### ISSUE TITLE
I found something awesome: Remotion 💯

### ISSUE THREAD

**Issue by mifi** [mifi/editly#118]
For those who haven't seen it yet.
Similar to editly but much more awesome:
Can use HTML and everything available in a browser:
https://www.youtube.com/watch?v=gwlDorikqgY
https://github.com/JonnyBurger/remotion

Note: It's not open source

**Comment by maddygoround** [comment]
Found this awesome library for FFmpeg animations and video overlay - [https://github.com/tnfe/FFCreator](https://github.com/tnfe/FFCreator)

**Comment by nabilfreeman** [comment]
Amazing! Very exciting to see this scene thriving. Gonna check this out.

**Comment by patcon** [comment]
Suuuuuper cool! Interestingly, license says free for small businesses. Wonder if they could be convinced to make it free for all worker co-operative businesses 😉 (haha vested interest on my part)

**Comment by mifi** [comment]
I just created a React based video editor too! It's still a bit beta, but check it out and let me know if it works! https://github.com/mifi/reactive-video

It's a lot faster than editly. It doesn't have so many features yet but the potential is really great!
