### ISSUE TITLE
Now there is no ffmpeg, what do we do for new builds?

### ISSUE THREAD

**Issue by doverradio** [mifi/editly#119]
hi, I recently completed a script that I was working on for awhile that is written with editly.

When I tried to install ffmpeg on the server I planned to put it, I found out the news that ffmpeg is no longer.

Is there a solution currently on this?

**Comment by mifi** [comment]
what do you mean by "ffmpeg is no longer"?

**Comment by doverradio** [comment]
https://www.reddit.com/r/AV1/comments/il4ag0/psa_zeranoes_ffmpeg_builds_are_going_offline_on/

This.

**Comment by mifi** [comment]
Oh. what about one of these linked from http://ffmpeg.org/download.html
- https://www.gyan.dev/ffmpeg/builds/
- https://github.com/BtbN/FFmpeg-Builds

**Comment by doverradio** [comment]
Ha thanks!  Had me buggin out over seeing that.  MY mistake.
