### ISSUE TITLE
WARNING: ffprobe issue: Invalid Version: 2021

### ISSUE THREAD

**Issue by ocean101** [mifi/editly#147]
WARNING: ffprobe issue: Invalid Version: 2021!    WARNING: ffprobe issue: Invalid Version: 2021 
And the video clips are extremely slow!    May I ask what's going on here?
And the video clips are extremely slow!    May I ask what's going on here?
And the video clips are extremely slow!    May I ask what's going on here?
Please help me out
Please help me out
Please help me out
Please help me out

**Comment by dalisoft** [comment]
For me similar issue?

```

**Comment by dalisoft** [comment]
@ocean101 I sure we should run `v4.3.1` as this version is MAX version allowed [[Source](https://github.com/mifi/editly/blob/19215f0de8e2276f5e4d8f18a839ad095a799349/ffmpeg.js#L17-L31)]

**Comment by mifi** [comment]
Actually the intention was that it requires MINIMUM version 4.3.1. I think this is a bug due to semver not supporting short versions (4.4)

**Comment by mifi** [comment]
ok i fixed this . try latest version
