### ISSUE TITLE
How to run in CLI mode?

### ISSUE THREAD

**Issue by githubtrip** [mifi/editly#148]
I am running this command but not working.
`editly --fontPath './assets/PatuaOne-Regular.ttf' --clip-duration 5 image.jpg --news-title 'NEWS TITLE' --subtitle 'NEWS SUBTITLE' --width 900 --height 1600 --out './news.mp4'`

This is based on this example file - https://github.com/mifi/editly/blob/master/examples/newsTitle.json5

Or is there any way to put the title and subtitle in dynamic way?

**Comment by mifi** [comment]
these are not valid command line arguments. See `editly --help` for how to run it. See https://github.com/mifi/editly#usage-command-line-video-editor

if you want to run a json file do this:
```
editly newsTitle.json5
```
