### ISSUE TITLE
[Question] Is that possible to use with ffprobe-static and ffmpeg-static?

### ISSUE THREAD

**Issue by BrunoQuaresma** [mifi/editly#153]
Hi, is that possible to use this package with [ffprobe-static](https://www.npmjs.com/package/ffmpeg-static) and [ffmpeg-static](https://www.npmjs.com/package/ffmpeg-static)?

**Comment by mifi** [comment]
Should be. You can try it, just specify the correct `ffmpegPath` and `ffprobePath` to editly

**Comment by BrunoQuaresma** [comment]
Thank you, it works! Sharing here a sample code in case anyone else has the same question.

```js
const editly = require("editly");
const ffmpegPath = require("ffmpeg-static");
const ffprobePath = require("ffprobe-static").path;

const editSpec = {
  ffmpegPath,
  ffprobePath,
  outPath: "output.mp4",
  width: 1642,
  height: 1642,
  ...
}
```
