### ISSUE TITLE
Somebody give me a hand!Somebody give me a hand!

### ISSUE THREAD

**Issue by ocean101** [mifi/editly#160]
I ran editly in nodeJS and got an error :
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'
Somebody give me a hand!
Somebody give me a hand!
Somebody give me a hand!
Somebody give me a hand!

**Comment by ocean101** [comment]
![image](https://user-images.githubusercontent.com/57646604/140314545-05f0d7ed-e113-45c2-a836-faa8016bc63e.png)
This is a screenshot of my error

**Comment by mifi** [comment]
please show your code if you want help

**Comment by ocean101** [comment]
> 我在 nodeJS 中编辑运行并得到一个错误： 无法在 'CanvasRenderingContext2D' 上执行 'drawImage'：提供的值不是类型 '(CSSImageValue 或 HTMLImageElement 或 SVGImageElement 或 HTMLVideoElement 或 HTMLCanvasElement 或 ImageBitmap 或 OffscreenCanvas)' 有人帮我一把！ 有人帮我一把！ 有人帮我一把！ 有人帮我一把！

**Comment by ocean101** [comment]
> 如果您需要帮助，请显示您的代码

![image](https://user-images.githubusercontent.com/57646604/140471765-40944b9f-5f9a-440b-a909-66f9cafbd1a9.png)

Take a look. This is my code

**Comment by ocean101** [comment]
> 如果您需要帮助，请显示您的代码
![image](https://user-images.githubusercontent.com/57646604/140482024-1adb35e6-6f67-47d1-898d-51a192490d19.png)
Please check it for me

**Comment by ocean101** [comment]
![image](https://user-images.githubusercontent.com/57646604/140482240-60be4c02-5f8f-4db4-aed4-f1cb16359639.png)

**Comment by mifi** [comment]
It may look like u are trying to run editly in the browser. That isn’t possible

**Comment by ocean101** [comment]
> 看起来您可能正在尝试在浏览器中以编辑方式运行。那不可能
Excuse me. How do I run it in JavaScript
