### ISSUE TITLE
Help me, I can't use editly above 0.5.0

### ISSUE THREAD

**Issue by ocean101** [mifi/editly#163]
I can't use editly0.5.0 or higher. I can't use Editly0.6.0 to 0.11.3, and it will give an error if I use it
![image](https://user-images.githubusercontent.com/57646604/145001161-794667b7-df5f-49c0-ac70-9f4a43bc89b3.png)

Help me！
Help me！
Help me！

**Comment by mifi** [comment]
please provide some code and steps how to reproduce

**Comment by ocean101** [comment]
![image](https://user-images.githubusercontent.com/57646604/145179027-309196ce-c1eb-4215-8fa3-55f7acf7f335.png)
![image](https://user-images.githubusercontent.com/57646604/145179149-3e968931-170d-4857-911b-94424a2c1984.png)
Take a look here's my code!

**Comment by mifi** [comment]
Seems a lot like #160

**Comment by ocean101** [comment]
I'm not using a browser to do this, it's normal to use editly0.5.0, this error occurs after 0.5.0
