### ISSUE TITLE
The value of "sourceEnd" is out of range

### ISSUE THREAD

**Issue by sanbroz** [mifi/editly#167]
While running editly --fast commonFeatures.json5 I am getting the following error

ffmpeg version 4.4.1
ffprobe version 4.4.1
Extracting audio/silence from all clips
Mixing clip audio with arbitrary audio
188x334 15fps
  0%   1%   2%   4%   5% Done with transition, switching to next transitionFromClip (1)
  7%   8%   9%  11%  12% Done with transition, switching to next transitionFromClip (2)
 14%  15%  16%  18% Done with transition, switching to next transitionFromClip (3)
 19%  21%  22%  24% Done with transition, switching to next transitionFromClip (4)
 25%  26%  28% Done with transition, switching to next transitionFromClip (5)
 29%  31%  32% Done with transition, switching to next transitionFromClip (6)
 33%  35%  36%  38% Done with transition, switching to next transitionFromClip (7)
 39%  40%  42%  43% Done with transition, switching to next transitionFromClip (8)
 45%  46%  48% Done with transition, switching to next transitionFromClip (9)
 49% Done with transition, switching to next transitionFromClip (10)
 50%  52%  53%  55% Done with transition, switching to next transitionFromClip (11)
 56%  57%  59% Done with transition, switching to next transitionFromClip (12)
 60%  62% Done with transition, switching to next transitionFromClip (13)
 63%  64%  66% Done with transition, switching to next transitionFromClip (14)
 67%  69%  70%  72% Done with transition, switching to next transitionFromClip (15)
 73%  74%  76%  77% Done with transition, switching to next transitionFromClip (16)
 79%  80%  81%  83% Done with transition, switching to next transitionFromClip (17)
 83%  84%  86%  87% node:buffer:227
      throw new ERR_OUT_OF_RANGE('sourceEnd', '>= 0', sourceEnd);
      ^

RangeError [ERR_OUT_OF_RANGE]: The value of "sourceEnd" is out of range. It must be >= 0. Received -20400
    at new NodeError (node:internal/errors:371:5)
    at _copy (node:buffer:227:13)
    at Buffer.copy (node:buffer:775:12)
    at Socket.handleChunk (C:\Users\user\AppData\Roaming\npm\node_modules\editly\sources\videoFrameSource.js:133:15)
    at Socket.emit (node:events:390:28)
    at Socket.Readable.read (node:internal/streams/readable:550:10)
    at Socket.read (node:net:644:39)
    at flow (node:internal/streams/readable:1035:34)
    at resume_ (node:internal/streams/readable:1016:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_OUT_OF_RANGE'
}

Node.js v17.3.0
av_interleaved_write_frame(): Invalid argument
Error writing trailer of pipe:: Invalid argument

**Comment by mifi** [comment]
Oww. That's a weird one. could you try node 16 and see if it helps? and possibly ffmpeg 4.3.x

**Comment by haiduong87** [comment]
I have same issue with node 16 (latest ffmpeg)

`ffmpeg version 2022
ffprobe version 2022
Extracting audio/silence from all clips
Mixing clip audio with arbitrary audio
188x334 15fps
  0%   1%   2%   4%   5% Done with transition, switching to next transitionFromClip (1)
  7%   8%   9%  11%  12% Done with transition, switching to next transitionFromClip (2)
 14%  15%  16%  18% Done with transition, switching to next transitionFromClip (3)
 19%  21%  22%  24% Done with transition, switching to next transitionFromClip (4)
 25%  26%  28% Done with transition, switching to next transitionFromClip (5)
 29%  31%  32% Done with transition, switching to next transitionFromClip (6)
 33%  35%  36%  38% Done with transition, switching to next transitionFromClip (7)
 39%  40%  42%  43% Done with transition, switching to next transitionFromClip (8)
 45%  46%  48% Done with transition, switching to next transitionFromClip (9)
 49% Done with transition, switching to next transitionFromClip (10)
 50%  52%  53%  55% Done with transition, switching to next transitionFromClip (11)
 56%  57%  59% Done with transition, switching to next transitionFromClip (12)
 60%  62% Done with transition, switching to next transitionFromClip (13)
 63%  64%  66% Done with transition, switching to next transitionFromClip (14)
 67%  69%  70%  72% Done with transition, switching to next transitionFromClip (15)
 73%  74%  76%  77% Done with transition, switching to next transitionFromClip (16)
 79%  80%  81%  83% Done with transition, switching to next transitionFromClip (17)
 83%  84%  86%  87% node:buffer:228
      throw new ERR_OUT_OF_RANGE('sourceEnd', '>= 0', sourceEnd);
      ^

RangeError [ERR_OUT_OF_RANGE]: The value of "sourceEnd" is out of range. It must be >= 0. Received -20400
    at new NodeError (node:internal/errors:372:5)
    at _copy (node:buffer:228:13)
    at Buffer.copy (node:buffer:776:12)
    at Socket.handleChunk (C:\Users\omnicasaservice\AppData\Roaming\npm\node_modules\editly\sources\videoFrameSource.js:133:15)
    at Socket.emit (node:events:527:28)
    at Socket.Readable.read (node:internal/streams/readable:527:10)
    at Socket.read (node:net:666:39)
    at flow (node:internal/streams/readable:1011:34)
    at resume_ (node:internal/streams/readable:992:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_OUT_OF_RANGE'
}`
