### ISSUE TITLE
Persian/Arabic font doesn't render correctly

### ISSUE THREAD

**Issue by l3est** [mifi/editly#171]
- [✅] I have tried with the newest version of editly: `npm i -g editly` or `npm i editly@latest`
- [✅] I have tried ffmpeg newest stable version
- [✅] I have searched for existing issues

here's the generated mp4 file:
https://user-images.githubusercontent.com/8002505/148548171-86f76edf-bec9-4174-aea0-751b9eae2470.mp4

here are the fonts I'm using.
BNazanin.ttf is the one used in the video. Lalezar-Regular.ttf has the same problem but the English characters are fine with Lalezar font.
[fonts.zip](https://github.com/mifi/editly/files/7828963/fonts.zip)

this is first slide's text:
هندزفری بلوتوثی مدل  inpods 12
and this is how it looks when it renders right:
![image](https://user-images.githubusercontent.com/8002505/148548711-19788d22-2feb-47cd-abd9-cace9b135588.png)
this is how editly renders the text:
![image](https://user-images.githubusercontent.com/8002505/148550323-3c9b6587-454e-401f-9f27-0b5311bd2401.png)

and this is my json5 file:
```
{
  width: 720,
  height: 720,
  outPath: './test.mp4',
  defaults: {
    layer: { fontPath: './BNazanin.ttf' },
  },
  clips: [
    { duration: 5, layers: [
      { type: 'image', path: './1.jpg' },
      { type: 'news-title', text: 'هندزفری بلوتوثی مدل  inpods 12' },
    ] },
    { duration: 5, layers: [
      { type: 'image', path: './2.jpg' },
      { type: 'news-title', text: 'نوع اتصال: بی‌سیم' },
    ] },
    { duration: 5, layers: [
      { type: 'image', path: './3.jpg' },
      { type: 'news-title', text: 'رابط‌ها: لایتنینگ' },
    ] },
    { duration: 5, layers: [
      { type: 'image', path: './4.jpg' },
      { type: 'news-title', text: 'نوع گوشی: دو گوشی' },
    ] },
    { duration: 5, layers: [
      { type: 'image', path: './5.jpg' },
      { type: 'news-title', text: 'عمر باتری محفظه شارژ 5 ساعت' },
    ] },
    { duration: 5, layers: [
      { type: 'image', path: './6.jpg' },
      { type: 'news-title', text: 'محدوده عملکرد 10 متر' },
    ] },
    { duration: 5, layers: [
      { type: 'image', path: './7.jpg' },
      { type: 'news-title', text: 'نسخه بلوتوث 5' },
    ] },
    { duration: 5, layers: [
      { type: 'image', path: './8.jpg' },
      { type: 'news-title', text: 'سفارش از طریق لینک موجود در توضیحات ویدیو' },
    ] },
  ],
}
```

**Comment by l3est** [comment]
do you have any plans to add support for languages like Persian/Arabic?

**Comment by mifi** [comment]
I don’t know what editly can do to specifically support arabic/persian. I think this is an issue with either fabric.js or (more likely I think) node-canvas. If you are able to isolate/reproduce the problem in one of those, then we can report an issue there.
Btw are you on MacOs, win or linux? Could you try a different operating system and see if it’s the same error

**Comment by l3est** [comment]
Ok here's what happened. I went through the issues again and found this one:
https://github.com/mifi/editly/issues/161
Urdu has similar text to Persian/Arabic (unlike English, letters in each word stick together) and I thought why does it look right in Urdu and not in Persian?
I thought maybe there is letter spacing in `news-title` type, and there was letter spacing.
I changed the `news-title` to `subtitle` and it alright now.
![image](https://user-images.githubusercontent.com/8002505/149515953-91f1382b-9057-496f-8aa3-5c886d828e3b.png)

so is there a way to pass on option reduce the letter spacing to 0 for `news-title`?

**Comment by mifi** [comment]
Letter spacing 0 is what’s solved your issue with  broken (rectangle) characters? Currently there isnt such an option but you can use the custom fabric layer and implement your own custom news title or subtitle

**Comment by l3est** [comment]
I used 2 fonts as I mentioned in my first post BNazanin and Lalezar-Regular, BNazanin doesn't support English letters (that doesn't have anything to do with editly, it's a font issue), the problem was messy Persian letters.
Thanks, I'm gonna implement my own news title

**Comment by mifi** [comment]
Ah ok. I misunderstood then! Thanks for reporting back on your solution
