### ISSUE TITLE
allowRemoteRequests now works with audio

### ISSUE THREAD

**Issue by lucemia** [mifi/editly#190]
I found out `allowRemoteRequests` options not work with audio currently.

https://github.com/mifi/editly/blob/9a19a890b0fa19642ed95ae51322499ade71d230/parseConfig.js#L21-L24

Is there any specific reason for that? if not, I opened a [PR](https://github.com/mifi/editly/pull/189) 

Thanks for the great project.

- [x] I have tried with the newest version of editly: `npm i -g editly` or `npm i editly@latest`
- [x] I have tried ffmpeg newest stable version
- [x] I have searched for existing issues

**Comment by mifi** [comment]
fixed by #189 - thanks
