### ISSUE TITLE
Layer as screenshot of a video

### ISSUE THREAD

**Issue by belavina** [mifi/editly#202]
I couldn't find this in the docs (sorry if I missed it) -- but is it possible to get a screenshot of a video as a layer type? I've tried:
```
              {
                type: 'video',
                cutFrom: 2,
                cutTo: 2,
                path: 'some-video.mp4',
              }
```
But `editly` complains about it with a message`cutFrom must be lower than cutTo`. I can always simply use `ffmpeg` but it would be nicer if it was supported out of the box with `editly`.

**Comment by mifi** [comment]
hi. i don't think that's supported without some custom code

**Comment by belavina** [comment]
Alright, thanks!
