### ISSUE TITLE
Is it possible to add sound effects to transitions?

### ISSUE THREAD

**Issue by rbaehr** [mifi/editly#208]
I'm wondering if anyone can think of a way to add sound effects during the clip transitions. I'm okay using a hacky workaround if anyone can think of any.

- [x] I have tried with the newest version of editly: `npm i -g editly` or `npm i editly@latest`
- [x] I have tried ffmpeg newest stable version
- [x] I have searched for existing issues

**Comment by mifi** [comment]
I think just use `audioTrack`, but you need to manually time the `start` of each audio clip to the transition.

**Comment by rbaehr** [comment]
> I think just use `audioTrack`, but you need to manually time the `start` of each audio clip to the transition.

Thanks, that did end up working. Although I ended up having to downgrade to 0.6.3 for performance reasons, so couldn't do that on the old version. Ended up just making a separate audio track afterward with silences in-between transitions and merging the audio with ffmpeg.
