### ISSUE TITLE
Adding hundreds of jpg pictures

### ISSUE THREAD

**Issue by blogdemoi** [mifi/editly#223]
Hello,

How can I add easily hundreds of jpg pictures from a unique folder?

I tried with a few pictures, for creating a sideshow and it works well, thank you for this tool:

`editly title:'My slideshow' 1.jpg 2.jpg 3.jpg 4.jpg 5.jpg 6.jpg	title:'THE END' --fast --audio-file-path /home/xxx/Desktop/f/vvvvv/1.mp3`

Bit what if I have hundreds of pictures?

**Comment by mifi** [comment]
does it not work if you try with 100s of pictures?

**Comment by blogdemoi** [comment]
> does it not work if you try with 100s of pictures?

I mean, how to list the jpgs in the command? I am not going to write `1.jpg 2.jpg .... 150.jpg` and so on :-)

**Comment by mifi** [comment]
use bash!

**Comment by blogdemoi** [comment]
Thank you.
`editly title:'My slideshow' *.jpg title:'THE END' --fast --audio-file-path xxx.mp3` worked fine.
