### ISSUE TITLE
How to increase font size in "News title" example?

### ISSUE THREAD

**Issue by szerzs-collab** [mifi/editly#225]
How to increase font size in "News title" example?
(in the screensh
![Screenshot_1](https://user-images.githubusercontent.com/80391399/216823217-1ed9b70f-a54b-4974-8aa3-965bd04051cd.png)
ot, the arrow indicates the text that needs to be enlarged)

**Comment by mifi** [comment]
no way to do that now, but you can copy the source code of the plugin and make your own plugin with larger size
