### ISSUE TITLE
Browser and WebAssembly

### ISSUE THREAD

**Issue by Immortalin** [mifi/editly#25]
https://github.com/ffmpegjs/ffmpeg.js#readme

**Comment by mifi** [comment]
I'm aware of that, but I don't know if it supports all features and codecs like x264. Also the performance may not be satisfactory. Someone needs to test it.

**Comment by Immortalin** [comment]
Hmmm, I will send a pull request. To clarify, the only methods where ffmpeg is called are those with "execa" imports right?

**Comment by mifi** [comment]
Yes. but there are other node specific apis being used that don't exist in a browser, like node-canvas

**Comment by Immortalin** [comment]
But we have a real Canvas in browser :)

**Comment by Immortalin** [comment]
@mifi is the plan for Lossless to use this library?

**Comment by mifi** [comment]
u mean LosslessCut? I have thought about it but I think if I make a GUI it will probably be a separate app because editly is so different from LosslessCut

**Comment by mifi** [comment]
Closing in favor of #90
