### ISSUE TITLE
Loop failed TypeError: Cannot read property 'ARRAY_BUFFER' of null

### ISSUE THREAD

**Issue by altrujade** [mifi/editly#29]
I got this error now:

$ editly test.json
960x1440 30fps
createFrameSource image clip 0 layer 0
createFrameSource image clip 1 layer 0
  0%   4%   8%  12%  16%  20%  25%  29% Loop failed TypeError: Cannot read property 'ARRAY_BUFFER' of null
    at runTransitionOnFrame (/usr/lib/node_modules/editly/glTransitions.js:19:10)
    at module.exports (/usr/lib/node_modules/editly/index.js:382:28)
    at async /usr/lib/node_modules/editly/cli.js:120:3

test.json:
{
 width: 960, height: 1440, fps: 30,
  outPath: './test.mp4',
  defaults: {
    transition: { name: 'fade' },
  },
  clips: [
    { duration: 3, layers: [{ type: 'image', path: './kornblume.jpg', zoomDirection: 'out' }] },
    { duration: 3, layers: [{ type: 'image', path: './chili.jpg', zoomDirection: 'in' }] },
    { duration: 3, layers: [{ type: 'image', path: './zucchini.jpg', zoomDirection: 'out' }] },
  ],
}

**Comment by mifi** [comment]
I think this is because some dependencies are missing.
See https://github.com/stackgl/headless-gl#system-dependencies
and https://github.com/stackgl/headless-gl/issues/162

I will add a better error message and update README.

**Comment by maerics** [comment]
Thanks for the updates here @mifi! I'm now seeing the [new "gl returned null" error](https://github.com/mifi/editly/commit/6a91e40ef5891aa16b044e52150eb177f928175c), still trying to figure out what's missing in my Linux image.

I'll open a new issue for that error with the Dockerfile I'm using in case others are interested.

**Comment by mifi** [comment]
I'll close this because #33
