### ISSUE TITLE
Errors installing

### ISSUE THREAD

**Issue by umaar** [mifi/editly#35]
Getting some errors when installing (node v14.0.0) with `npm i -g editly`

```
> canvas@2.6.1 install /usr/local/lib/node_modules/editly/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-darwin-unknown-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@14.0.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
```

It errors out and doesn't get installed.

**Comment by chapmanjacobd** [comment]
https://github.com/mifi/editly#requirements

the error says: pkg-config: command not found

**Comment by tukkajukka** [comment]
I had similar problems too. A quick workaround was to downgrade Node.

**Comment by mifi** [comment]
Ohh it seems because node-canvas doesn't provide prebuilt binaries for node 14 yet, so it tries to build from source, but then you need to have build tools installed. Added to readme.

**Comment by PanMan** [comment]
I needed to install `pango` (which fortunately came as a homebrew package).
