### ISSUE TITLE
CustomFabricSoure does not accept parameters

### ISSUE THREAD

**Issue by santhoshtr** [mifi/editly#37]
The `func` value set of `type:fabric` customFabricFrameSource does not recieve any parameters. For example, you cannot pass a text to https://github.com/mifi/editly/blob/master/examples/customFabric.js.

Following patch can fix it.

```
diff --git a/sources/fabricFrameSource.js b/sources/fabricFrameSource.js
index 74b8299..c88238c 100644
--- a/sources/fabricFrameSource.js
+++ b/sources/fabricFrameSource.js
@@ -308,7 +308,7 @@ async function createCustomCanvasFrameSource({ width, height, params }) {
 }
 
 async function customFabricFrameSource({ canvas, width, height, params }) {
-  return params.func(({ width, height, fabric, canvas }));
+  return params.func(({ width, height, fabric, canvas, params }));
 }
 
 function registerFont(...args) {
```

**Comment by willhalling** [comment]
Thanks for this. I was looking for a way to add to multiple fabric elements to the page so I need the params to work.

@mifi I have a video where I need more than one custom fabric element. Is there a better approach than using params?

By the way, amazing library by the way, very impressive.

**Comment by mifi** [comment]
@willhalling I'm not sure I understand what you need. I agree params could be nice!

**Comment by mifi** [comment]
Now implemented. thanks
