### ISSUE TITLE
resume a broken render or check that all files exist before encoding

### ISSUE THREAD

**Issue by chapmanjacobd** [mifi/editly#39]
I think it would be useful to check that all files exist. maybe someone types a path wrong or something. if it's not too much trouble it would be good to check that all the referenced files (video, shaders, audio) exist

normally this wouldn't be a big deal but if someone starts a long render process then it is a little bit annoying to realize that one of the assets is missing.

alternatively, some code which will allow resuming from a partial render would satisfy this issue and would be amazing!

**Comment by mifi** [comment]
Agree. This is not too hard to implement.

**Comment by mifi** [comment]
I think this only applies to the `image` and `gl` type?

**Comment by chapmanjacobd** [comment]
yes. you are correct
