### ISSUE TITLE
location of example assets?

### ISSUE THREAD

**Issue by jonklein** [mifi/editly#43]
I may have missed something, but I'm not able to find the assets required by the examples, so I'm not able to run any of them.  Are they available as a separate download somewhere?

**Comment by mifi** [comment]
I didn't want to include the sample assets in this repository because they are quite huge and I don't want everyone who downloads the repo to have to download hundreds of megabytes. But I'm thinking about putting them in a separate github repo and then having a download script from here.

**Comment by mifi** [comment]
I have now included all needed assets. See https://github.com/mifi/editly/tree/master/examples#examples

**Comment by whatneuron** [comment]
I am unable to find them as well :(
