### ISSUE TITLE
How to change the font-size?

### ISSUE THREAD

**Issue by heinhoang** [mifi/editly#46]
Is there any option for font size of text layer?

**Comment by gary149** [comment]
You cannot change it directly with the api. However it's not too difficult to make your own fabric layer, check how it is done internally:https://github.com/mifi/editly/blob/d4bd8fe544753c2c3ed31fbc1927fed6bfd2ddb4/sources/fabricFrameSource.js#L207

**Comment by heinhoang** [comment]
thanks gary149
