### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by OfekA** [mifi/editly#53]
I'm running editly in a docker container using the JS API.
It's running inside an express handler and memory usage goes very high when rendering and stays at about 80% of it's highest peak after the video has rendered, and stays that way after it has done executing, never coming down unless restarting the container.

When I comment out the editly call, there is no memory leak:
```js
await editly(editlySpec);
```

Here is my editlySpec:
```js
let editlySpec = {
    outPath: '/usr/src/app/assets/video/movie.mp4',
    width: 1708,
    height: 960,
    defaults: {
      transition: { name: 'fade', duration: 0.525 },
      duration: 1.05
    },
    clips:[
       { layers: [{ type: 'image', path: '/usr/src/app/assets/video/000.png', zoomDirection: null, zoomAmount: 0 }] },
       { layers: [{ type: 'image', path: '/usr/src/app/assets/video/001.png', zoomDirection: null, zoomAmount: 0 }] },
       ....
       { layers: [{ type: 'image', path: '/usr/src/app/assets/video/019.png', zoomDirection: null, zoomAmount: 0 }] }
    ],
    enableFfmpegLog: false,
    verbose: false
  };
```

The PNGs are 1708 × 960 and ~2MB each.

Any idea why this might happen?

Edit:
Migrated to using the CLI for now until this is fixed, the issue doesn't happen to me when using it.

**Comment by mifi** [comment]
I'm not sure how Node.js manages memory, but it could just be that it never releases memory until needed and is working as intented.

**Comment by OfekA** [comment]
I ran it in the AppEngine environment, so maybe node works a bit differently there. I wonder if anyone else has experienced anything like this since in my situation the memory was never released properly and the instance had to be restarted often.

Anyways, as I mentioned I'm running it using the CLI and it works great :)

**Comment by ariel-frischer** [comment]
I'm running into the same issue on Node v12.16.2 & v12.18.2 I've tested this on both linux and windows environments actually getting some huge memory leaks when converting one image to a video ~600mb increase. This also happens inside a ubuntu 18.04 docker environment and outside the docker environment. When I combine multiple videos (2-6) together the resident set size of Node process increased by about 100 mb. I tried exposing node garbage collector and using that, it does not work, increasing max-old-space-size param for node just will have it last longer until memory leak overcomes that set value. It took me a while to figure out what the memory leak is I'm using both fluent-ffmpeg, alongside editly, the significant memory increases only happen after the editly calls.

**Comment by smith1302** [comment]
I've been experiencing this as well. After the videos are rendered the memory is not released by the Node JS process. Creating multiple videos eventually causes an OOM crash because of the stacked memory. Tested using the 'fill-color' layer type, so it does not seem to be images layers only with the issue.

As ariel mentioned it doesn't seem to be happening if only using video layers, so it may be an issue specifically with layers that use fabric to a canvas to image conversion. I'll try to dive in further to see where the memory leak might be happening...

**Comment by smith1302** [comment]
After some more investigating it seems that a canvas object might be getting retained somehow. I uncommented the `canvas.dispose()` line here and it seemed to fix the leak:
https://github.com/mifi/editly/blob/master/sources/fabricFrameSource.js#L34

I don't have much experience with canvas or node, @mifi do you have any context around the dispose line being commented out?

**Comment by mifi** [comment]
Thanks for the research @smith1302
I think I read somewhere that it was not necessary to call dispose. But I may have misunderstood. Since it seems to help, I will uncomment it 👍

**Comment by mifi** [comment]
I think this one is solved. Closing for now
