### ISSUE TITLE
Video layer position

### ISSUE THREAD

**Issue by matthewturk** [mifi/editly#54]
Hi!  I love using editly.  I'm interested in contributing a patch to it to enable mosaicing of images, similar to:

https://trac.ffmpeg.org/wiki/Create%20a%20mosaic%20out%20of%20several%20input%20videos

If this were to be staged out I think the order would be something like:

 - [x] Add a layer size option for video sources
 - [x] Add a layer position option for video sources
 - [x] (much harder) allow multiple video sources in a single clip, either as multiple layers or a "multi-video" source

But before I began, I was wondering if this was something you'd thought about, and if you'd be open to a PR along these lines *if* I'm able to make it work.

Thanks!

**Comment by FOSSforlife** [comment]
+1

If we could position multiple videos/images within the same clip (especially if we could loop them as well, for animated clipart and things like that), I'd use editly for all my YouTube podcast uploads. This would be a game changer.

**Comment by mifi** [comment]
Would be nice, but I think it might be better to do with fabric.js rather than ffmpeg, as fabric gives more flexibility.

**Comment by mifi** [comment]
This one is now implemented! See https://github.com/mifi/editly/blob/master/examples/mosaic.json5

**Comment by matthewturk** [comment]
:fireworks: :clap: This is awesome!
