### ISSUE TITLE
customFabric.js example not working - Loop failed TypeError: Cannot set property 'backgroundColor' of undefined

### ISSUE THREAD

**Issue by over9001** [mifi/editly#57]
Thank you for this fun software!
I am using gitlab-ci to run editly and experiencing some success. Exciting!
However, nothing I have tried has been able to make the example customFabric.js work correctly or output anything.
Getting the examples in this project to run without assets is a serious challenge/hurdle for new users, but I'm used to pain of this kind with new code, so I powered through getting it set up. Now I'm really stuck!

Please help me get this working, or understand why it's failing. Thank you!

This is the section of the log that shows customCanvas.js succeeding, and customFabric.js failing:
$ xvfb-run -s "-ac -screen 0 1280x1024x24" node ./exampleCustomCanvas.js
320x320 10fps
createFrameSource gl clip 0 layer 0
createFrameSource canvas clip 0 layer 1
  0%  50% Done with transition, switching to next clip
No more transitionFromClip, done
Done. Output file can be found at:
./output/customCanvas.gif
$ xvfb-run -s "-ac -screen 0 1280x1024x24" node ./exampleCustomFabric.js
320x320 10fps
createFrameSource fabric clip 0 layer 0
Loop failed TypeError: Cannot set property 'backgroundColor' of undefined
    at Object.onRender [as readNextFrame] (/builds/petroff.ryan/editly-cloud/exampleCustomFabric.js:7:28)
    at Object.readNextFrame (/builds/petroff.ryan/editly-cloud/node_modules/editly/sources/frameSource.js:40:38)
    at module.exports (/builds/petroff.ryan/editly-cloud/node_modules/editly/index.js:356:45)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Here's my .gitlab-ci.yml, in case that is important:
image: node:latest

before_script:
  - apt-get update -qq && apt-get install -y mesa-utils xvfb libgl1-mesa-dri libglapi-mesa libosmesa6 ffmpeg node-gyp libpangocairo-1.0-0 libcairo2-dev libjpeg-dev libgif-dev libpango1.0-dev libxi-dev libxext-dev libx11-dev libgl1-mesa-dev

build:
  script:
    - npm install
    - npm i -g editly --unsafe 
    - xvfb-run -s "-ac -screen 0 1280x1024x24" editly ./examplegl.json5
    - xvfb-run -s "-ac -screen 0 1280x1024x24" node ./exampleCustomCanvas.js
    - xvfb-run -s "-ac -screen 0 1280x1024x24" node ./exampleCustomFabric.js
    - xvfb-run -s "-ac -screen 0 1280x1024x24" editly ./exampleSubtitle.json5

  artifacts:
    paths:
      - output/

npm install installs gl and editly. Am I missing a dependency? Please help me figure this out :) 
Thank you!

**Comment by smith1302** [comment]
From the error, it looks like "canvas" is undefined or null.

Try modifying the fund method from
`async function onRender(progress) {`
to
`async function onRender(progress, canvas) {`

**Comment by over9001** [comment]
Thank you thank you thank you! 
This was the change I needed, and now it works!

Who are you, who are so wise in the ways of science?!

Does this mean that it's not just me, and actually no one has been able to successfully run that example?

THANK YOU!!!

**Comment by gregzanch** [comment]
I just submitted a pull request (#64) which uses the solution supplied by @smith1302

**Comment by mifi** [comment]
Thanks. I believe this is now solved.
