### ISSUE TITLE
Performance idea

### ISSUE THREAD

**Issue by swlemp** [mifi/editly#59]
I have no need to resize, re-encode, adjust FPS or otherwise modify input videos.
All I do is use glsl transitions between these videos.

I get the sense extracting frames and re-encoding from what should only be stream copied
is slowing down editly by a factor of 10.  The width/height and FPS of the transitions
can be inferred from the greater source video (or be defined manually?).

For the purpose of increasing performance, is it possible to trim input videos up to the point
the transition starts, copy what was trimmed out, and start encoding where the trim/transition
begins only, and then concat everything?

Edit: I'm going to try this concept out by running editly multiple times on the transition junctions
only and see what that does for the processing time.  Fingers crossed.

**Comment by swlemp** [comment]
@mifi I followed the process above and my processing time went from >= 2 hours to <= 5 minutes!

**Comment by mifi** [comment]
I think this would be awesome but it is really out of the scope of editly, because editly focuses on advanced compositing, and not just simple concatenation. Could probably make a separate project for that use case.
