### ISSUE TITLE
Support HTTP(S) paths

### ISSUE THREAD

**Issue by MDrooker** [mifi/editly#60]
This may be an enhancement-
But is it possible to have the image path point to a http/https url?
So it could look like -
```
clips: [
            {
                duration: 10, layers: [
                    { type: 'image', path: 'https://cdn.cnn.com/cnnnext/dam/assets/200723190801-02-fauci-opening-pitch-exlarge-169.jpg' },
                    { type: 'news-title', text: 'BREAKING NEWS' },
                    { type: 'subtitle', text: 'Lorem ipsum dolor.', backgroundColor: 'rgba(0,0,0,0.5)' }
                ]
            },
        ],
```

Thanks

**Comment by srameshr** [comment]
@mifi I have done this using Sharp. I can send a PR if you have not started on this.

**Comment by maksym-plotnikov** [comment]
It's an easy fix IMHO.
You can just check inside sources/fabricFrameSource.js:loadImage:60 something like:
```
const loadImage = async (path) => new Promise((resolve) => {
  const filePath = path.startsWith('http') ? path : fileUrl(path);
  return fabric.util.loadImage(filePath, resolve);
});
```

since fabric.util.loadImage acepts both type of file urls

**Comment by srameshr** [comment]
@maksym-plotnikov 
In my case I had to resize the images to match the video width and height as it breaks the code if both the source(image) & destination (video) is not of the same width.

**Comment by maksym-plotnikov** [comment]
@mifi with Fabric You can try to resize images by it's biggest size (choosing width or height) and scale by this parameter. Something like that:

```
const sX = canvas.width / img.width;
const sY = canvas.height / img.height;
if (sX > sY) {
    img.scaleToWidth(
        img.getScaledWidth() * (sX / img.scaleX),
    );
} else {
    img.scaleToHeight(
        img.getScaledHeight() * (sY / img.scaleY),
    );
}
```
@srameshr sure You need to feed assets in the same sizes to "editly" ATM.  BTW if You're working with MacOS you will have issues with Sharp and node-canvasIt our team we had to switch from `sharp` to `Jimp` for such reason.

**Comment by mifi** [comment]
Hi. I'm not sure what sharp or Jimp has to do with this. And why is `fileUrl` needed? I saw there is another PR which also includes this funcitonality, but there is no fileUrl call:
https://github.com/mifi/editly/pull/61/files

And it shouldn't be necessary to feed the same size, as editly will automatically scale images to fit the screen, or is it different with URLs? In the newest version I have added an image-overlay type which is a raw image that can be custom sized and positioned also.

**Comment by maksym-plotnikov** [comment]
> editly will automatically scale
@mifi as far as I can see  - `editly` only scales image by width so if You add  landscape image to portrait oriented canvas ()e.g. canvas is 1080x1920 and image is 1920x1080) or vice versa You will have blank areas around image:
![image](https://user-images.githubusercontent.com/35142461/94019750-cccdb880-fdba-11ea-909e-3e449c302e82.png)

**Comment by srameshr** [comment]
@maksym-plotnikov I am on Mac and sharp works without any hiccups. It does work great with all linux distros as well.

**Comment by maksym-plotnikov** [comment]
It not problem with `sharp` - it should be combo with node-canvas + sharp - https://github.com/Automattic/node-canvas/issues/1386. But glad that you don't have any issues. It was just a experience sharing from my side :)

**Comment by mifi** [comment]
I have implemented better scaling options in the latest commit

**Comment by mifi** [comment]
Have now implemented this. Needs a flag `allowRemoteRequests` / `--allow-remote-requests`.
