### ISSUE TITLE
Provide feature to add logo both on image and video layers.

### ISSUE THREAD

**Issue by srameshr** [mifi/editly#69]
A common requirement is to add a 150x150 logo on any of the screen corners. Instead of using canvas to construct one, it would be simpler if a logo could be added via a layer. Currently the option with image-overlay does not work as the image occupies the whole screen.

**Comment by mifi** [comment]
Oops I forgot to add documentation for the `width` and `height` params. They are 0-1 (relative to video width/height)

I will update the readme.

| Parameter  | Description | Default | |
|-|-|-|-|
| `path` | Path to image file | | |
| `position` | See [Position parameter](#position-parameter) | | |
| `width` | Width (from 0 to 1) where 1 is screen width | | |
| `height` | Height (from 0 to 1) where 1 is screen height | | |

**Comment by srameshr** [comment]
@mifi The position parameters are ignored for everything apart from x:0, y:0
Want our logo at the bottom right and none of the below combination works
{x:0, y: 0, originX: 'right', originY: 'bottom'}
{x:1, y: 1, originX: 'right', originY: 'bottom'}

**Comment by mifi** [comment]
Oh is it working? Why did you close this?

**Comment by srameshr** [comment]
Sorry, that comment was by mistake. But its working. Il send a PR to update the README.

**Comment by mifi** [comment]
No need for PR, I already updated (in a branch)
