### ISSUE TITLE
Loop audio to match the length of generated video instead of breaking it.

### ISSUE THREAD

**Issue by srameshr** [mifi/editly#71]
Right now if the total length of generated video (via clips) is say 60 seconds and the length audio file is smaller than the video then it breaks with the below error. Please supporting looping of audio to match the length of the video.
```
```

**Comment by mifi** [comment]
Can you provide a more complete example? I don't know what 34.204.204.190 port 22 has to do with editly

**Comment by srameshr** [comment]
The IP address was pasted by mistake. 
So, the bug is if the video that is constructed from clips is say of length 60 seconds and the length of the audio file provided via audioFilePath is less than 60 seconds the execution breaks with an EPIPE error. How about looping the audio file to match the length of the video being constructed?

**Comment by mifi** [comment]
Ok, I'm looking into that error. I agree looping is a good solution

**Comment by mifi** [comment]
This is now implemented with a flag `loopAudio` / `--loop-audio`. Will release new version soon.
