### ISSUE TITLE
Error: Property 'filter' undefined (Windows)

### ISSUE THREAD

**Issue by pi43r** [mifi/editly#74]
I am getting the following Error message on Windows 10 CLI
Will try again with WSL, but I'd like to understand the error. What does it mean?

```
Caught error TypeError: Cannot read property 'filter' of undefined
    at pMap.concurrency (C:\Users\USER\AppData\Roaming\nvm\v12.18.2\node_modules\editly\index.js:138:32)
    at C:\Users\USER\AppData\Roaming\nvm\v12.18.2\node_modules\editly\node_modules\p-map\index.js:57:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by mifi** [comment]
Can I see your edit spec json?

**Comment by pi43r** [comment]
You mean this, right?

```
{
  outPath: './out.mp4',
  width: 1280,
  height: 720,
  fps: 25,
  keepSourceAudio: true,
  defaults: {
    duration: 2,
  },
  // Testing options:
  enableFfmpegLog: false,
  verbose: false,
  fast: false,
  clips: [
    'M:/Direct/Path/to/image.jpg',
    'M:/Direct/Path/to/image.jpg',
    'M:/Direct/Path/to/image.jpg',
  ],
}
```

**Comment by mifi** [comment]
Yea, this json is invalid. You need to follow the format in readme. see also examples.

**Comment by pi43r** [comment]
Gotcha!
The images have to be in the following format: 
`{ layers: [{ type: 'image', path: './assets/pano.jpg' }] },`

Thanks for the help!
I suggest to create a friendly error message for that, but I guess this is not urgent :)

**Comment by mifi** [comment]
NP. I have now improved the error messages/validation a bit
