### ISSUE TITLE
Broken video files

### ISSUE THREAD

**Issue by pi43r** [mifi/editly#77]
I really love the idea of that tool, but I a can not get it to work on my windows machine.
It produces files and doesn't give me any errors. The mp4 files have a bigger filesize when more clips are selected, but the file is broken for any program. GIFs will output 0 bytes.
https://drive.google.com/file/d/1QppskwMZvfzd3nmuw_FZj75vtbJRWIMj/view?usp=sharing

What can it be? Broken GL renderer or something?
I reinstalled/updated ffmpeg which didn't change anything.

Using 
Windows 10 Powershell
FFMPEG 4.2
editly 0.6

PS: It would be cool if you could upload the assets/ folder to the examples

**Comment by mifi** [comment]
could you post the output when running with --verbose ? and also your edit spec?

**Comment by pi43r** [comment]
I used the commonFeauters.json5 file and changed the font, images and audio. I also deleted the GL examples.
Examples with no input (gradients.json5) also do not produce playable output.

Output can be found in the txt file attached. No error messages except:
`[mov,mp4,m4a,3gp,3g2,mj2 @ 00000188f1acdfc0] stream 0, timescale not set` which has to do with m4a audio as far as I understood.
[common_output.txt](https://github.com/mifi/editly/files/5288281/common_output.txt)

**Comment by TimoGruber** [comment]
i have the same issue with no error message. Using ```fast: true``` works with the same video files for me, so maybe it has something to do with the defaults or input file formats.

**Comment by mifi** [comment]
How long is Track4.m4a ? Could you try without it? Are you running newest version? @TimoGruber what's the resolution (seen from --verbose) with and without fast: true.

It would be helpful if you can provide a minimal as simple as possible editSpec that can reproduce the problem.

**Comment by mifi** [comment]
I have now included all needed assets. See https://github.com/mifi/editly/tree/master/examples#examples

**Comment by pi43r** [comment]
It works now!
I think it might have been an issue with my node version. I don't know which one I was using before, but I switched to 14.13 before I ran the example scripts.
Thanks for uploading, you are doing amazing work.

I will close this and Timo could start a new Issue, if he still has the problem.
