### ISSUE TITLE
Video sound is delayed

### ISSUE THREAD

**Issue by fangyishui** [mifi/editly#87]
I used multiple pictures and videos to synthesize the video, but why the sound of the original video is delayed.

**Comment by mifi** [comment]
Please provide your JSON spec and/or output from `editly --verbose` and which version of editly you are using

**Comment by fangyishui** [comment]
Thinks mifimifi
 my editly version is 0.7.1,
json5:
`{
    "width": 360,
    "height": 640,
    "outPath": "112233_3.mp4",
    "keepSourceAudio": true,
    "allowRemoteRequests": true,
    "fast": false,
    "clips": [{
            "transition": {
                "name": "doorway"
            },
            "layers": [{
                    "type": "image",
                    "path": "http://pic.sc.chinaz.com/files/pic/pic9/202010/apic28427.jpg"
                }
            ]
        }, {
            "transition": {
                "name": "doorway"
            },
            "layers": [{
                    "type": "image",
                    "path": "http://pic1.sc.chinaz.com/files/pic/pic9/202010/apic28425.jpg"
                }
            ]
        }, {
            "transition": {
                "name": "doorway"
            },
            "layers": [{
                    "type": "image",
                    "path": "http://pic.sc.chinaz.com/files/pic/pic9/202010/bpic21602.jpg"
                }
            ]
        }, {
            "transition": {
                "name": "doorway"
            },
            "layers": [{
                    "type": "image",
                    "path": "http://pic.sc.chinaz.com/files/pic/pic9/202010/apic28263.jpg"
                }
            ]
        }, {
            "transition": {
                "name": "doorway"
            },
            "layers": [{
                    "type": "image",
                    "path": "http://pic.sc.chinaz.com/files/pic/pic9/202010/apic28298.jpg"
                }
            ]
        }, {
            "transition": {
                "name": "doorway"
            },
            "layers": [{
                    "type": "image",
                    "path": "http://pic2.sc.chinaz.com/files/pic/pic9/202010/apic28655.jpg"
                }
            ]
        }, {
            "transition": {
                "name": "doorway"
            },
            "layers": [{
                    "type": "image",
                    "path": "http://pic.sc.chinaz.com/files/pic/pic9/202010/apic28662.jpg"
                }
            ]
        }, {
            "transition": {
                "name": "doorway"
            },
            "layers": [{
                    "type": "image",
                    "path": "http://pic.sc.chinaz.com/files/pic/pic9/202010/apic28316.jpg"
                }
            ]
        }, {
            "transition": {
                "name": "doorway"
            },
            "layers": [{
                    "type": "video",
                    "path": "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4"
                }
            ]
        }
    ]
}`

**Comment by fangyishui** [comment]
the video sound delay 2 to 3 seconds

**Comment by mifi** [comment]
same problem on newest version?

Also can you try with this version?
```
npm install -g mifi/editly#master
```

**Comment by mifi** [comment]
I just tested your json5 with master and there is no delay

**Comment by fangyishui** [comment]
Yeah, you're right. I upgraded to 0.11.0,there is no delay.

Thank you very much mifi
