### ISSUE TITLE
Add GIF with ‘image-overlay’

### ISSUE THREAD

**Issue by fangyishui** [mifi/editly#88]
gif won't move

**Comment by mifi** [comment]
Have you tried `video` type instead?

**Comment by fangyishui** [comment]
yeah This is my json5
`{
  outPath: 'Overlay.mp4',
  clips: [
    { layers: [
      { type: 'video', path: 'D:/media/weishi/mp4/2.mp4'},
      { type: 'image-overlay', path: 'T0001.gif',width:0.2,position: { x: 0.95, y: 0.03, originX: 'right' } },
     ] },
  ],
}`

**Comment by mifi** [comment]
I mean liek this

```
[
  { layers: [
    { type: 'video', path: 'D:/media/weishi/mp4/2.mp4'},
    { type: 'video', path: 'T0001.gif', width:0.2, position: { x: 0.95, y: 0.03, originX: 'right' } },
  ]}
]


```

**Comment by fangyishui** [comment]
An error occurred
` The value of "sourceEnd" is out of range. It must be >= 0. Received -49152`

**Comment by mifi** [comment]
Are you running newest editly version? Can you try the attached `cat.gif` and this JSON5:

```js
{
  width: 300, height: 300,
  outPath: './gif-input.mp4',
  clips: [
    { layers: [{ type: 'video', path: './assets/cat.gif', width:0.2, height: 0.2, left: 0.95, top: 0.03, originX: 'right' }] },
  ],
}
```

![cat](https://user-images.githubusercontent.com/402547/98116054-06104280-1ea8-11eb-850a-5e8f7a86245b.gif)

**Comment by fangyishui** [comment]
Yeah My version is 0.11.0，
You may have misunderstood，I want to add gifs to the video

**Comment by mifi** [comment]
So this doesn't work?

```js
{
  width: 300, height: 300,
  outPath: './gif-input.mp4',
  clips: [
    { type: 'video', path: 'D:/media/weishi/mp4/2.mp4'},
    { layers: [{ type: 'video', path: './cat.gif', width:0.2, height: 0.2, left: 0.95, top: 0.03, originX: 'right' }] },
  ],
}
```

**Comment by fangyishui** [comment]
Is the way you write it right ， there video no layers
‘Caught error AssertionError [ERR_ASSERTION]: "clip.layers" must contain one or more objects
    at pMap.concurrency (C:\Users\yetech\AppData\Roaming\npm\node_modules\editly\parseConfig.js:116:5)
    at C:\Users\yetech\AppData\Roaming\npm\node_modules\editly\node_modules\_p-map@4.0.0@p-map\index.js:57:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='’

**Comment by fangyishui** [comment]
Let me write it this way so I can add，
but gif duration is very short can it be extended

**Comment by mifi** [comment]
Ops I mistyped. Updated json now

**Comment by mifi** [comment]
For now you have to repeat the layer if you want to loop the gif:

```js
{
  width: 300, height: 300,
  outPath: './gif-input.mp4',
  clips: [
    { layers: [
      { type: 'video', path: 'D:/media/weishi/mp4/2.mp4'},
      { type: 'video', path: './cat.gif', width:0.2, height: 0.2, left: 0.95, top: 0.03, originX: 'right' },
      { type: 'video', path: './cat.gif', width:0.2, height: 0.2, left: 0.95, top: 0.03, originX: 'right', start: 1.3 },
    ] },
  ],
}
```

Maybe we could implement a loop option for video layers also. I'll create an issue for that.

**Comment by fangyishui** [comment]
what is mean is 'start'

**Comment by mifi** [comment]
see readme `clips[].layers[].start`  **What time into the clip should this layer start**

**Comment by fangyishui** [comment]
Does the GIF have a survival time,
I try add the gif fps，but the gif 6s at most。
So,I just loop the gif ?

**Comment by mifi** [comment]
yes you can loop the gif yourself

**Comment by fangyishui** [comment]
Well, that's about it
Thinks mifi

**Comment by fangyishui** [comment]
I tried the svg format but it didn't work.
So I want to make it like tiktok, can there be a lot of animation effects,

**Comment by mifi** [comment]
svg is not a video, you need to use image-overlay.  See https://github.com/mifi/editly/blob/master/examples/imageOverlay.json5

**Comment by fangyishui** [comment]
I tried this, but it doesn't move

**Comment by fangyishui** [comment]
@mifi

**Comment by mifi** [comment]
what do you mean not move? is it an animated svg? can you provide a sample file?

**Comment by fangyishui** [comment]
[https://dadao.cyou/SAMPLE%20PROJECT.svg](url)

**Comment by fangyishui** [comment]
Or I just want to add dynamic pictures to the video, Is there no other way?

**Comment by mifi** [comment]
Oh cool. I actually never seen an animated SVG before I think. ffmpeg doesn't seem to support this. I found you can use [this tool](https://github.com/tungs/timecut) to convert it to mp4 for use in editly:

```
npm i -g timecut
timecut SAMPLE\ PROJECT.svg
```

**Comment by mifi** [comment]
I opened a new issue for animated svg  #92. Closing this because gif seems to work.

**Comment by fangyishui** [comment]
ok , good job
