### ISSUE TITLE
image-overlay doesn't seem to use start when using node.js

### ISSUE THREAD

**Issue by JoePlant** [mifi/editly#91]
I am looking to have an image with 4 squares that appear in the corners after 1 second each.

When I run this from the command line it works but when the same code is run in node it seems to not use the start parameters for the image overlay.

image-overlay.json5

```
  {
    width: 320, height:320,
    enableFfmpegLog: false,
    verbose: false,
    // fast: true,
    fps: 30,
    allowRemoteRequests: true,
    outPath: './test.gif' ,
    defaults: {
      duration: 5,
    },
    clips:[
        {
        duration:5,
        layers: [
            { type: 'rainbow-colors'},
            { type: 'image-overlay', path: 'https://placeimg.com/800/800/any', position: 'top-left', start: 1,  width: 0.3 , zoomDirection: 'in'},
            { type: 'image-overlay', path: 'https://placeimg.com/800/800/any', position: 'top-right', start: 2,  width: 0.3 , zoomDirection: 'in'},
            { type: 'image-overlay', path: 'https://placeimg.com/800/800/any', position: 'bottom-left', start: 3,  width: 0.3 , zoomDirection: 'in'},
            { type: 'image-overlay', path: 'https://placeimg.com/800/800/any', position: 'bottom-right', start: 4,  width: 0.3 , zoomDirection: 'in'},
        ]
      }
    ]    
  }
```

When this is run from the command line it works:

```
editly image-overlay.json5

ffmpeg version 4.3.1
ffprobe version 4.3.1
320x320 15fps
  0%  13%  26%  40%  53%  66%  80%  93% Done with transition, switching to next transitionFromClip (1)
No more transitionFromClip, done

Done. Output file can be found at:
./test.gif
```

![test](https://user-images.githubusercontent.com/4065727/99037228-03f86300-25cf-11eb-9ca9-4c42206ee543.gif)

Same picture when running in node.js

test.js

```
'use strict';

const editly = require('editly');

var video_params = {
    width: 320, height:320,
    enableFfmpegLog: false,
    verbose: false,
    // fast: true,
    fps: 30,
    allowRemoteRequests: true,
    outPath: './test-code.gif' ,
    defaults: {
      duration: 5,
    },
    clips:[
        {
        duration:5,
        layers: [
            { type: 'rainbow-colors'},
            { type: 'image-overlay', path: 'https://placeimg.com/800/800/any', position: 'top-left', start: 1,  width: 0.3 , zoomDirection: 'in'},
            { type: 'image-overlay', path: 'https://placeimg.com/800/800/any', position: 'top-right', start: 2,  width: 0.3 , zoomDirection: 'in'},
            { type: 'image-overlay', path: 'https://placeimg.com/800/800/any', position: 'bottom-left', start: 3,  width: 0.3 , zoomDirection: 'in'},
            { type: 'image-overlay', path: 'https://placeimg.com/800/800/any', position: 'bottom-right', start: 4,  width: 0.3 , zoomDirection: 'in'},
        ]
      }
    ]    
 }

editly(video_params).catch(console.error);
```
Executing using node:
```
320x320 15fps
  0%  13%  26%  40%  53%  66%  80%  93% Done with transition, switching to next transitionFromClip (1)
No more transitionFromClip, done

Done. Output file can be found at:
./test-code.gif

```

First file is correct (test.gif) running from the command line using json5 file, the 2nd file is incorrect (test-code.gif) when using node.js.

![test](https://user-images.githubusercontent.com/4065727/99037228-03f86300-25cf-11eb-9ca9-4c42206ee543.gif)
![test-code](https://user-images.githubusercontent.com/4065727/99037369-49b52b80-25cf-11eb-9c4a-713d5465d8a5.gif)

- [x] I have tried with the newest version of editly: `npm i -g editly`
- [x] I have tried ffmpeg newest stable version
- [x] I have searched for existing issues

**Comment by mifi** [comment]
Please double check that you are using the latest version. (`npm i editly` in your project)
`cat node_modules/editly/package.json | grep version`
I renamed `visibleFrom` to `start` in a recent version.

**Comment by JoePlant** [comment]
@mifi thanks for your help.  I am still learning the node.js environment.  My node module was editly 0.10.2 which had the old parameter.  I also installed it globally which seems to explain why only the command line version of the file was working correctly.

Also when I checked, the command `npm i editly` would not update the editly version.  It was still 0.10.2 after running this..

To get the latest version I ended up uninstalling editly and then reinstalling which pulled down the most up to date version.
`npm uninstall editly`
and 
`npm install editly`

It now works.  Thanks for a great package.  
Maybe you can add the version number to the output messages (you already include the ffmpeg and ffprobe versions already).

Also maybe it might be good to update the issue template because it will depend on whether people are using the globally installed command line or the local node module.

**Comment by mifi** [comment]
that's alright. keep learning! and thanks for putting time into making a great bug report. i'll update the issue template and see if i can add a version print out
