### ISSUE TITLE
Multiple audio tracks over image.

### ISSUE THREAD

**Issue by Atlas7005** [mifi/editly#99]
Hey, I'm using the Node.js Library and I have this idea that I wanna try out. But I really am confused by how this entire thing works...
So, I wanna make a video with 5 songs and 1 background image, each song plays after the other until there are no more, at which point the video should end.

This is what I got (idx is just so I can keep track of the videos):
```js
var editly = require("editly");
var fs = require("fs");

var idx = 0;

var editObj = {
	enableFfmpegLog: true,
	outPath: "./vids/"+idx+".mp4",
	width: 1280,
	height: 720,
	fps: 24,
	defaults: {
		transition: null
	},
	clips: [
		{
			layers: [
				{
					type: "image",
					path: "./bgs/"+idx+".jpg"
				}
			]
		}
	],
	audioTracks: fs.readdirSync("./audio/"+idx+"/").map(song => {
		return { path: "./audio/"+idx+"/"+song };
	})
};

(async function() {
	await editly(editObj).then(console.log).catch(console.error);
})();
```

**Update:**
Current Code:
```js
var editly = require("editly");
var duration = require("mp3d");
var fs = require("fs");

var idx = 0;

var editObj = {
	enableFfmpegLog: true,
	outPath: "./vids/"+idx+".mp4",
	width: 1280,
	height: 720,
	fps: 24,
	defaults: {
		transition: null
	},
	clips: [
		{
			layers: [
				{
					type: "image",
					path: "./bgs/"+idx+".jpg"
				}
			]
		}
	],
	audioTracks: fs.readdirSync("./audio/"+idx+"/").map((song, index, arr) => {
		if(index == 0) {
			var obj = { path: "./audio/"+idx+"/"+song, start: 0 };
			return obj;
		} else {
			var obj = { path: "./audio/"+idx+"/"+song };
			duration("./audio/"+idx+"/"+arr[index-1], async (err, result) => {
				obj.start = Number((result / 1000).toFixed(0));
			});
		}
	})
};

```

**Comment by mifi** [comment]
hi. you need to offset the audio tracks start position by the duration of the previous audio (imagine like a timeline in a video editor)

**Comment by Atlas7005** [comment]
How would I do that?

> hi. you need to offset the audio tracks start position by the duration of the previous audio (imagine like a timeline in a video editor)

**Comment by mifi** [comment]
see `start` in the main documentation: https://github.com/mifi/editly#arbitrary-audio-tracks

**Comment by Atlas7005** [comment]
Alright. I'll see what I can do. But I might need help.

**Comment by Atlas7005** [comment]
Yeah. I really don't know how I would do this. Is it possible you(or someone else) could spoonfeed me a bit?

**Comment by Atlas7005** [comment]
This is what I have now...
```js
var editly = require("editly");
var duration = require("mp3d");
var fs = require("fs");

var idx = 0;

var editObj = {
	enableFfmpegLog: true,
	outPath: "./vids/"+idx+".mp4",
	width: 1280,
	height: 720,
	fps: 24,
	defaults: {
		transition: null
	},
	clips: [
		{
			layers: [
				{
					type: "image",
					path: "./bgs/"+idx+".jpg"
				}
			]
		}
	],
	audioTracks: fs.readdirSync("./audio/"+idx+"/").map((song, index, arr) => {
		if(index == 0) {
			var obj = { path: "./audio/"+idx+"/"+song, start: 0 };
			return obj;
		} else {
			var obj = { path: "./audio/"+idx+"/"+song };
			duration("./audio/"+idx+"/"+arr[index-1], async (err, result) => {
				obj.start = Number((result / 1000).toFixed(0));
			});
		}
	})
};
```

**Comment by mifi** [comment]
here is an example spec:

(given winxp.mp3 has a duration of 10 sec and you want to play it 3 times)

```
    { path: './assets/winxp.mp3', start: 0 },
    { path: './assets/winxp.mp3', start: 10 },
    { path: './assets/winxp.mp3', start: 20 },
```

**Comment by Atlas7005** [comment]
I know how to use the editly stuff. I just don't know how I would make it dynamic, as seen in the code above.
I'm reading the files in a directory, getting their duration using the node library [mp3d](https://www.npmjs.com/package/mp3d). But it returns a Promise, and I don't really know how I would create the object and then return it to the `Array.map` function.

**Comment by Atlas7005** [comment]
**Update:**
I fixed the duration stuff. But the entire video's duration is still only 4 seconds.

**Comment by Atlas7005** [comment]
> **Update:**
> I fixed the duration stuff. But the entire video's duration is still only 4 seconds.

Fixed this as well. Thanks.

**Comment by mifi** [comment]
cool! would be niceif you shared your solution in case someone else hits the same problem
